name: Release Tag (goreleaser and container image)

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: sigstore/cosign-installer@v3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: goreleaser-dist
          path: dist/
  docker-image:
    needs:
      - goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Fetch build artifacts
        uses: actions/download-artifact@v4
        with:
          name: goreleaser-dist
      - name: Display structure of downloaded files
        run: ls -R
