name: Release Tag (goreleaser and container image)

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: sigstore/cosign-installer@v3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: goreleaser-dist
          path: dist/
  docker-image:
    needs:
      - goreleaser
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch build artifacts
        uses: actions/download-artifact@v4
        with:
          name: goreleaser-dist
          path: dist/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
      - name: Build and push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        id: build-push
        with:
          context: .
          file: package/Dockerfile
          platforms: "linux/amd64,linux/arm64,linux/s390x"
          push: true
          tags: ${{ env.IMAGE_REPO }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}